version: '3.8'

services:
  db:
    image: postgres:15
    container_name: predict-db
    environment:
      POSTGRES_DB: predict_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: predict-api
    ports:
      - "8081:8080"  # Host 8081 -> Container 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/predict_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
